FROM nginx:stable-alpine
COPY ../../composeApp/build/dist/wasmJs/productionExecutable/* /usr/share/nginx/html/wasmJs/
COPY ../../composeApp/build/dist/js/productionExecutable/* /usr/share/nginx/html/js/
COPY ../../composeApp/webdelegate/* /usr/share/nginx/html/
